### ISSUE TITLE
Standardize the way we handle 400/regular/normal/italic font weight 

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/customify#133]
Ar trebui sa putem folosi prin orice configurare 400 si sa fie tradusa in valoarea necesara fontului ales (400, regular sau normal).

**Comment by georgeolaru** [comment]
@vladolaru I think you already did some improvements on the latest revision of the whole plugin. 

Do you consider this issue still relevant or we can close it?

**Comment by vladolaru** [comment]
@georgeolaru I haven't tackled this particular "translation" between font weights according to each font. So it is still relevant.
