### ISSUE TITLE
Font Palettes - Third Iteration (Introduce intent)

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/customify#137]
Incerc sa introduc o serie de controale care sa introduca conceptul de in intentie a unei palete de fonturi astfel incat sa controlam impactul pe care il are asupra stilului final.

In situatia curenta, paleta nu controleaza si nu influenteaza font-size-ul.

**Comment by georgeolaru** [comment]
@vladolaru Do you think we can close this and open a new issue when we're getting closer to new iterations on the Font Palettes system?

**Comment by vladolaru** [comment]
Sure @georgeolaru
