### ISSUE TITLE
Update documentation to match new Customizer sections organization - shop themes

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/customify#140]
O data cu update-ul la 1.7.4 care include [reorganizarea](https://github.com/pixelgrade/customify/issues/139) sectiunilor din Customizer trebuie sa updatam si documentatia temelor cu noile locatii. De ex. `Appearance > Main Content > ...` devine `Appearance > Theme Options > Main Content > ...`

Toate sectiunile introduse de teme se muta in panoul **Theme Options**.

Propun ca intai sa facem modificarile doar la documentia temelor de pe shop, si apoi la celelalte.

- [ ] Vasco
- [ ] Julia
- [ ] Felt
- [ ] Silk
- [ ] Gema
- [ ] Patch
- [ ] Hive

@pixelgrade/heroes @georgeolaru

**Comment by vladolaru** [comment]
@alinclamba Poti prelua tu aici?

**Comment by alinclamba** [comment]
@vladolaru sigur că da, mersi de heads-up.

**Comment by georgeolaru** [comment]
@alinclamba Mai e valabil acest issue sau putem sa-l inchidem?

**Comment by alinclamba** [comment]
Eu am uitat de acest issue, îmi pare rău. @madalingorbanescu pregătește un update pentru Customify și așa a dat peste el. Știu că în ultima perioadă, @andreiungurianu s-a ocupat în mod special de documentație. Andrei, ne poți spune dacă ai pe lista ta și asta?

**Comment by andreiungurianu** [comment]
Salutare. Eu am făcut săptămâna trecută update pe următoarele articole care se intersectau cu opțiunile descrise mai sus:

- [Personalize your site appearance](https://pixelgrade.com/docs/rosa/design-and-style/personalize-site-appearance/)
- [Changing Colors](https://pixelgrade.com/docs/rosa/design-and-style/changing-colors/)
- [Changing Fonts](https://pixelgrade.com/docs/rosa/design-and-style/changing-fonts/)

Singurele care mai sunt în categoria _Design and Style_ sunt [Theme Customizer](https://pixelgrade.com/docs/timber/design-and-style/theme-customizer/) (valabil pentru Timber), [Portfolio Grid](https://pixelgrade.com/docs/noah/design-and-style/portfolio-grid/) (valabil pentru Noah) și [Post Titles Styling](https://pixelgrade.com/docs/hive/design-and-style/post-titles-styling/) (valabil pentru Hive). Le pot trece și pe astea două pe listă să mă asigur că indicațiile se potrivesc cu locul setărilor.

În rest, e posibil să mai fie zone din Theme Options - General (ca cele legate de Google Maps API), însă pe măsură ce voi ajunge și la articolele respective, mă voi ocupa de ele.

Eu zic că după ce verific articolele menționate de mine, pot închide issue-ul.

**Comment by vladolaru** [comment]
Bun asa @andreiungurianu 

PS: This is public so we should be using English. But since this is a previously opened issue, I will let it slide :)

**Comment by andreiungurianu** [comment]
Hello. I managed to update all of these three articles that I mentioned above. It seems like all of them were outdated regarding the location of the settings from the Customizer.

I also managed to edit the video from [Portfolio Grid ](https://pixelgrade.com/docs/noah/design-and-style/portfolio-grid/), replacing the settings pannel with the new updated one.
