### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method Customify_Customizer::instance()

### ISSUE THREAD

**Issue by lelik4w** [pixelgrade/customify#170]
Appears upon plugin activation and won't allow activating it.
Please find below the entire error log:

Fatal error: Uncaught Error: Call to undefined method Customify_Customizer::instance() in /var/www/vhosts/.../wp-content/plugins/customify/includes/class-pixcustomify.php:128 Stack trace: #0 /var/www/vhosts/.../wp-content/plugins/customify/includes/class-pixcustomify.php(103): PixCustomifyPlugin->init() #1 /var/www/vhosts/.../wp-content/plugins/customify/includes/class-pixcustomify.php(932): PixCustomifyPlugin->__construct('/var/www/vhosts...', '2.5.0') #2 /var/www/vhosts/.../wp-content/plugins/customify/customify.php(35): PixCustomifyPlugin::instance('/var/www/vhosts...', '2.5.0') #3 /var/www/vhosts/.../wp-content/plugins/customify/customify.php(40): PixCustomifyPlugin() #4 /var/www/vhosts/.../wp-admin/includes/plugin.php(2141): include('/var/www/vhosts...') #5 /var/www/vhosts/.../wp-admin/plugins.php(175): plugin_sandbox_scrape('customify/custo...') #6 {main} thrown in /var/www/vhosts/.../wp-content/plugins/customify/includes/class-pixcustomify.php on line 128

**Comment by vladolaru** [comment]
@lelik4w Thank you for reporting this issue.

I have tested and looked at possible scenarios where this might occur, and all I could find would be if someone else would declare the `Customify_Customizer` class before (maybe another plugin or theme). I have changed the class name to be more specific, but I don't think there is something else to be done.
