### ISSUE TITLE
Warnings on Timber

### ISSUE THREAD

**Issue by allexsava** [pixelgrade/customify#18]
fixul la om este in customify/class-pixcustomify.php
linia 639 inlocuita cu asta
if ( $load_all_weights && isset( $value['variants'] ) && ! empty( $value['variants'] ) ){

![image](https://cloud.githubusercontent.com/assets/3309914/8787699/44e5789a-2f3e-11e5-88dc-84fcc884c8b9.png)

**Comment by allexsava** [comment]
Done @andreilupu :camel:

**Comment by andreilupu** [comment]
:+1:
