### ISSUE TITLE
WordPress notification regarding Customify Error

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/customify#182]
Since WordPress 5.2, there is a built-in feature that recognizes when a plugin or theme causes a fatal error on your site and that notifies you with this automatic email.

In this case, WordPress has found a problem with Customify:

> Error details
> ===========
> An error of type E_ERROR was caused on line number 725 of the file /var/www/vhosts/124/339010/webspace/siteapps/WordPress-630906/htdocs/wp-content/plugins/customify/includes/class-pixcustomify.php . Error message: Uncaught Error: Call to a member function get_plugin_setting () on null in / var / www / vhosts / 124/339010 / webspace / site apps / WordPress-630906 / htdocs / wp-content / plugins / customify / includes / class-pixcustomify .php: 725
> Stack trace:
> 0 /var/www/vhosts/124/339010/webspace/siteapps/WordPress-630906/htdocs/wp-content/plugins/customify/includes/class-pixcustomify.php(361): PixCustomifyPlugin-> get_option ('sm_font_palette' , NULL, Array)
> 1 /var/www/vhosts/124/339010/webspace/siteapps/WordPress-630906/htdocs/wp-content/plugins/customify/includes/class-pixcustomify.php(590): PixCustomifyPlugin-> get_options_details (false, false )
> 2 /var/www/vhosts/124/339010/webspace/siteapps/WordPress-630906/htdocs/wp-content/themes/rosa2/inc/integrations/customify/extras.php(30): PixCustomifyPlugin-> get_options_configs ()
> 3 /var/www/vhosts/124/339010/webspace/siteapps/WordPress-630906/htdocs/wp-content/themes/rosa2/inc/extras.php(271): pixelgrade_option ('sm_dark_mode', 'off')
> 4 / var / www / vhosts / 124/339010 / webspace / site apps / WordPress-630906 / htdo

Theme — Rosa 2

**Comment by vladolaru** [comment]
Here I suspect that the minimal PHP version was not met. Customify needs PHP 5.3+. There is a notification for this, but since it triggers a fatal error, that notification is not seen by the user.

**Comment by vladolaru** [comment]
I added a further check and a tag in the readme.txt file, but I can't be sure it will remove all issues when the minimal PHP version is not met.

**Comment by alinclamba** [comment]
@vladolaru thanks for checking. Just a note — in the specific case mentioned, the PHP version was **7.2.22**. Maybe it helps.

**Comment by vladolaru** [comment]
Thanks @alinclamba
