### ISSUE TITLE
Font weight does not save properly

### ISSUE THREAD

**Issue by Alexandru-Teodorescu** [pixelgrade/customify#189]
Când schimbi fontul în (exemplu: Montserrat) și selectezi font weight (exemplu: 600), fontul se salvează  corect. Dacă intri din nou în Customizer și te duci înapoi să schimbi font weight-ul, atunci font weight-ul se schimbă automat în 100.

Am testat pe temele Pile și Rosa 1, acolo am putut reproduce. 

Video: https://cl.ly/a3980acac886

**Comment by madalingorbanescu** [comment]
Atat Pile, cat si Rosa folosesc inputul de tip `typography`, asta fiind o varianta mai veche pentru selectorul de fonturi. Temele mai noi folosesc `font` si problema asta nu mai apare.

La temele mentionate, o data cu integrarea Font Palettes, va veni si noul tip de selector, deci va rezolva problema.

**Comment by vladolaru** [comment]
Asta cred ca am rezolvat-o cu schimbarile recente.
