### ISSUE TITLE
Developer license

### ISSUE THREAD

**Issue by KienTrong** [pixelgrade/customify#19]
Hey, nice works guys.
Does the license of it allow us to includes Customify into our theme that available for sale on TF or our own theme shop?

Regards.

**Comment by vladolaru** [comment]
Hi,

Yes you surely can use Customify as a recommended or required plugin via TGM or other options. It is a GPL v2 license so you can whatever you want with it. It would be nice if you would share back with us what you've been up to (fork would be best if you intend to modify it).
