### ISSUE TITLE
Sticky Header doesn't work on the Live Site

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/customify#191]
In Customize Live Preview, if choosing the Sticky menu it works. But when you check the live site, the menu isn't sticky.

**Comment by madalingorbanescu** [comment]
Issue-ul era pentru **Rosa2**, nu pentru Customify, dar dupa o verificare mai amanuntita, pare ca defapt nici nu este issue.

Header-ul poate fi sticky, doar cand pe pagina exista destul de mult content cat sa permita un header sticky. In cazul clientului respectiv, pe pagina era doar un slider.
