### ISSUE TITLE
Cloud Font Palettes Library

### ISSUE THREAD

**Issue by razwan** [pixelgrade/customify#194]
Hey,

I added some palettes to the cloud library for testing purposes. However, the font palettes aren't very consistent at the moment.

1. First, there are the palettes used for **Rosa2**, which are a pretty consistent group. But at the moment the local fonts functionality doesn't exist. They work in Rosa2 because the fonts are registered through **Customify** by the theme.
2. Second, we have the font palettes for **Gema**, **Hive**, **Patch** and **Julia** which are again quite a consistent group, but the main difference is they have only three main fonts, lacking the accent font.
3. Third, I managed to find some initial implementations for the font palettes for themes, like **Fargo**, **Osteria**, **Felt**, **Pile**, **Listable**, but their final implementation uses a reset functionality without declaring font logic. The main suspect here is **Vasco** which really can't be obtained using any fonts logic. We certainly could create a reset palette for each theme, the question that remains if any of the salvaged palettes above would be available for any other themes considering the majority of these palettes also don't have an accent font assigned.

@georgeolaru, @vladolaru any though on what would be the next steps to make?

**Comment by georgeolaru** [comment]
@razwan Good questions! I appreciate the insights and the proposal that you've made. 

I suggest not to go bottom-to-top and make individual themes palettes available for other themes (eg. from Osteria to All Themes); if we will be able to go the other way around and add support for generic palettes to older themes (eg. Osteria) that would be great and could make some customers happy. 

For now on, I would like to focus the entire Font Palettes library on the Rosa2 and descending future themes. For other themes, a "Default font palette" that simply resets the configuration should be the way to go.

In my opinion, the next steps should be:
1. You with @vladolaru prepare all the fonts from the [Staff Picks](https://www.google.com/url?sa=t&rct=j&esrc=s&source=appssearch&uact=8&cd=0&cad=rja&q&sig2=KfE34u_uRcbFuGn120F5OQ&ved=0ahUKEwj-zcWt0LroAhWPqlAKHcUaD2s4ABABKAAwAA&url=https://drive.google.com/a/pixelgrade.com/open?id%3D1Y8Oufj9Xxrnbvsa1C21vf2gOZ3F2jlOAMBvZTB3i_IQ%26usp%3Dchrome_omnibox&usg=AOvVaw3JDH1tjQy4bqXNF6jpP3Dd) list and make them consistently available (including the local ones).
2. I will propose [here](https://docs.google.com/spreadsheets/d/1Y8Oufj9Xxrnbvsa1C21vf2gOZ3F2jlOAMBvZTB3i_IQ/edit#gid=1292011072) an initial list of font palettes following the Rosa2 template as reference: **primary**, **secondary**, **body** and **accent fonts**.
3. You will take the list above and do the necessary set up to make it available in all the themes that have support for Font Palettes (starting with Rosa2).

Let me know if this sounds like a plan, so I can move forward and start putting together an initial batch of font palettes.

**Comment by vladolaru** [comment]
An update here @georgeolaru @razwan . I have put live the ability to configure Cloud Fonts on cloud.pixelgrade.com

**Comment by georgeolaru** [comment]
That's great @vladolaru! Thanks

@razwan It seems that yesterday I forgot to press the _Send_ button and the message is now lost 😢  I will rewrite a short update again.

I created the first batch of 4 fonts palettes: **Lacrima**, **Patrick**, **Edward**, and **Alpina**:

![image](https://user-images.githubusercontent.com/1632775/78131321-9161bb00-7423-11ea-88d9-28fa14e1f712.png)
- All the details are in the Google Spreadsheet [file](https://docs.google.com/spreadsheets/d/1Y8Oufj9Xxrnbvsa1C21vf2gOZ3F2jlOAMBvZTB3i_IQ/edit#gid=1292011072)
- The thumbnail images are on [this](https://drive.google.com/open?id=1JHbxh6RrYmnDpP-MdjKl-Iyc5KrKAv6k) Google Drive folder
- And here are the [Figma mockup](https://www.figma.com/file/VrF62MaRjrunRNKU0jnDWDa9/Plugin-Style-Manager?node-id=436%3A469) for reference

Let me know once you get an initial draft that I can test and in the meantime I will move forward with other proposals.

**Comment by vladolaru** [comment]
@georgeolaru @razwan where do we stand here?

**Comment by georgeolaru** [comment]
@vladolaru With the latest Rosa2 [update](http://wupdates.com/rosa2-changelog) (April 29, 2020), we have released all four font palettes mentioned above.  They work very well even if there are some adjustments that I would like to make to the config — but we will take care of that through the [Pixelgrade Cloud](https://github.com/pixelgrade/pixelgrade-cloud/issues).

@razwan Needs to make a decision if it is reasonable to hope and have them integrated into the other themes. 

---

Concerning the functionality related to the Customify plugin and the goal that we have with this issue, I think we're finished and we can close this issue. Well done! 🙏
