### ISSUE TITLE
Navigation font weight not applying

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/customify#198]
It seems like the font-weight applied on the Navigation Menu font does not apply.

I experienced this while customizing the Rosa 1 theme. When I go to Appearance -> Customize -> Theme Options -> Fonts - Navigation and change the font-weight from 100 to 900, it saves and applies, but when I return to the Customizer it resets back to 100.

I'm using Customify 2.6.0.

**Comment by vladolaru** [comment]
This is fixed also with the recent refactoring and cleaning.
