### ISSUE TITLE
[Font Palettes] Add support for font size boost value in fonts logic

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/customify#217]
We want to be able to define both at master font control level (e.g., for `sm_font_primary`) and at font interval level, a font size boost coefficient. 

This will be a float value that will get multiplied with the font size value in the font palettes calculations. Most of the time this value will be between zero and two (e.g., `0.8`, `1.2`, `1.5`). The default value will be `1`, meaning no effect.

We will use the `font_size_boost` key in the fonts logic configuration.

**Comment by vladolaru** [comment]
There you go @georgeolaru

**Comment by georgeolaru** [comment]
Nice work @vladolaru! I just tested and this fonts stuff's really getting there 🤩 

![CleanShot 2020-05-21 at 14 52 23](https://user-images.githubusercontent.com/1632775/82556609-c3191780-9b72-11ea-8b25-c7c58c0fd9be.gif)


As we discussed, are you willing to change the name to `font_size_factor`? In the meantime, I will adjust the "Pandora" (0.8) and "Edward" (1.2) palette to take into account this functionality.

**Comment by vladolaru** [comment]
As discussed, we will use `font_size_multiplier`.

**Comment by vladolaru** [comment]
Done @georgeolaru

**Comment by georgeolaru** [comment]
Awesome! I changed through the Cloud font palettes and we can close this 👏
