### ISSUE TITLE
Selected fonts does not render properly

### ISSUE THREAD

**Issue by Alexandru-Teodorescu** [pixelgrade/customify#223]
O dată cu trecerea la Customify 2.9.0 a aparut o problema la încărcarea Google Fonts. 

Un exemplu ar fi atunci când schimbi fontruile de la meniu din Customizing > Theme Options > Fonts. În live preview se schimbă (https://share.getcloudapp.com/jkuQEEx2) dar după ce salvezi, se adaugă un font pe care nu l-ai selectat. https://share.getcloudapp.com/ApuAEx6O

Screenshot: https://share.getcloudapp.com/nOue59mL

**Comment by vladolaru** [comment]
@Alexandru-Teodorescu I believe this is the same bug as in #224. I've already fixed that. 

PS: Please use English.
