### ISSUE TITLE
Bug when loading google fonts

### ISSUE THREAD

**Issue by arnaud16571542** [pixelgrade/customify#224]
Hello Guys,

I spotted a bug with the plugin with Google Font.
Everything was running fine with the 2.8.0 version of plugin. Error occured with version 2.9.0.

When loading the google font, i got the HTTP 400 error code. See the request sent below from Customify:

https://fonts.googleapis.com/css2?family=Source%20Sans%20Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&family=Herr%20Von%20Muellerhoff:ital,wght@0,400&family=Raleway:ital,wght@0,100;0,700;0,200;0,900;0,300;0,400;0,800;0,500;0,600;1,800;1,700;1,500;1,600;1,100;1,400;1,300;1,200;1,900&family=Raleway:ital,wght@0,100;0,700;0,200;0,900;0,300;0,400;0,800;0,500;0,600;1,800;1,700;1,500;1,600;1,100;1,400;1,300;1,200;1,900&display=swap

See the Google's server response below:
- 400: Invalid selector
- Tuples must be sorted
- Raleway:ital,wght@0,100;0,700;0,200;0,900;0,300;0,400;0,800;0,500;0,600;1,800;1,700;1,500;1,600;1,100;1,400;1,300;1,200;1,900

Google docs is saying tuple must be sorted numerically...Seem to be the case for the 1st tuple, but not the 2nd.
https://developers.google.com/fonts/docs/css2

Best Regards,
Arnaud

**Comment by vladolaru** [comment]
Hi Arnaud,

Thank you for letting us know about it. I'll get right on it.

**Comment by vladolaru** [comment]
Found the bug and fixed it. It will be included shortly in the 2.9.1 update.

**Comment by arnaud16571542** [comment]
Hello Vlad,

Thank you for your fast work! I confirm this bug is corrected, Google Fonts are loading correctly now !

Have a nice day!

**Comment by vladolaru** [comment]
Thank you for getting back to us! It helps to know we've covered your situation. 

Have a nice day
