### ISSUE TITLE
Update Customify config for Gutenberg integration

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/customify#227]
While testing our themes with the latest version of WordPress, I saw that options set in Customify where not applying in editor anymore.

After inspecting the Page Source, I've realized that the CSS is outputted, but not valid. The reason for not being valid anymore is the fact that editor mark-up had suffered some changes. More info about that can be found [here](https://github.com/WordPress/gutenberg/pull/19050/files).

Currently Customify is generating an inline CSS using the old class _.editor-block-list__block_

The issue was not visible in our latest theme Rosa2, because on that theme we are using only :root selector and Customify is not prefixing this.

**Comment by vladolaru** [comment]
I guess we can consider this fixed @madalingorbanescu
