### ISSUE TITLE
Check and fix Customizer controls styling with new WP version

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/customify#228]
Since we introduce a custom styling of the Customizer sidebar (panels, sections, etc), we need to check to see how it is behaving, especially on lower resolution screens and mobile devices. I've noticed certain situations with sections that didn't look right.

We should do a full review and fix anything that is not quite right.

**Comment by madalingorbanescu** [comment]
Hey @vladolaru,

While testing Customify on smaller resolutions I couldn't find any issues, just a few improvements that can be made:  
- [ ] Font selector - when there is no font selected on hover, text color should be white: [image](https://user-images.githubusercontent.com/46342490/93853344-65c9da00-fcbc-11ea-89b1-d065294802d7.png)
- [ ] Checkbox is not consistent - sometimes is square, sometimes is round.
- [ ] On/off toggle is too big and label is not aligned: [image](https://user-images.githubusercontent.com/46342490/93857367-25218f00-fcc3-11ea-8a59-0107f7899bd5.png)

Can you help me with some screenshots of the sections that were not looking right? It will help me a lot.

**Comment by vladolaru** [comment]
Yep. It seems I can't reproduce them anymore.

**Comment by madalingorbanescu** [comment]
Closed in https://github.com/pixelgrade/customify/commit/d1d606dc3b0e9554caf785c37b14fd49796f2ce7
