### ISSUE TITLE
Enhance the Dark Mode toggle to take into account device settings

### ISSUE THREAD

**Issue by razwan** [pixelgrade/customify#230]
Quoting @georgeolaru from an issue opened on Rosa2:

>I think we should transform the "Dark Mode" functionality from the Customizer to an "Appearance" radio group with three options: **Light** (default), **Dark**, and **Auto** ( with the following description "Set light or dark mode automatically, according to the system-wide setting"). 
>
>![image](https://user-images.githubusercontent.com/1632775/97161099-fdbc5700-1785-11eb-9598-ad4750717c8a.png)
>
>Regarding the **switcher** from the navigation, there are a few use cases, depending on the "Appearance" option:
>1. When the "Appearance" option is set to "Light" or "Dark", the switcher will take those options as a _default_. When pressed it will change to the other one.
>2. When the "Appearance" option is set to "Auto", the switcher will use the system option to reflect the current state (Dark or Light). When the user uses this switcher for the first time, it will override the "Auto" mode and the user will be able to manually commute between those two states.
>
>I hope it makes more sense now.
>
>---
>As a side note, we could use the macOS setting as a reference ([User Guide](https://support.apple.com/guide/mac-help/use-a-light-or-dark-appearance-mchl52e1c2d2/mac))
>
>![image](https://user-images.githubusercontent.com/1632775/97160505-21cb6880-1785-11eb-82ef-97bd4b643a2a.png)

**Comment by georgeolaru** [comment]
@madalingorbanescu or @vladolaru As mentioned [here](https://github.com/pixelgrade/rosa2/issues/169#issuecomment-716609562), I think it makes sense to explain each one of those options, or at least the "Auto" by adding the following description:
> "Set light or dark mode automatically, according to the system-wide setting"
