### ISSUE TITLE
CSS Editor field is broken when WooThemes Helper plugin is used

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/customify#32]
**CSS Editor** din Customizer devine inoperabil daca activezi  [WooTheme Helper](https://docs.woothemes.com/document/woothemes-helper/)

![screenshot_1192](https://cloud.githubusercontent.com/assets/6790170/13925374/b401c54a-ef90-11e5-8e2f-157c1ae6848d.png)

**Comment by andreilupu** [comment]
CSS Editor is bye bye now
