### ISSUE TITLE
Can't use backslash in CSS editor field

### ISSUE THREAD

**Issue by Robertght** [pixelgrade/customify#33]
Daca incerc sa fortez o iconita cu content:"\F0d5" de exemplu, dupa refresh "\" o sa dispara si o sa lase numai F0d5.

N-am testat mai multe cazuri, dar in asta nu merge

**Comment by raduconst** [comment]
Da, dar merge sa pui "\\f0d5" (testat acum)

**Comment by andreilupu** [comment]
subiect outdated #48
