### ISSUE TITLE
Dependent Fields

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/customify#35]
O solutie sa afisam un field in functie de valoarea unui select/checkbox.

Am facut un research si am gasit plugin-ul asta care s-ar putea sa ne ajute ca punct de start: https://github.com/znbailey/jQuery-Dependent-Fields

Imi place sintaxa si cred ca putem incepe prin a scrie config-ul intr-un fisier separat in functie de tema:
`$('#navigation-trigger-text').dependsOn('#navigation-trigger-format', 'text');`

Ce ziceti @andreilupu @vladolaru ?

**Comment by andreilupu** [comment]
In mare parte vreau sa applic un callback de partial-refresh pe fiecare field(sau doar pe cele inter-dependente) ca sa pot avea access la [noile evenimente](https://make.wordpress.org/core/2016/02/16/selective-refresh-in-the-customizer) din customizer.

Cat despre partea de jQuery nu stiu cat de buna e libraria aia veche de 5 ani :D principala problema e ca merge doar cu _checkboxes_ si _selects_  pe cand noi o sa avem nevoie pentru _radio_, _multiple selects_, _inputs_, _textareas_, etc.

Propuneri:

-  [dependsOn](http://dstreet.github.io/dependsOn/)
- si atat, am mai gasit doua dar ori sunt mai vechi, ori nu imi place sintaxa

**Comment by georgeolaru** [comment]
Suna bine — daca te pot ajuta cu ceva sa-mi spui :)

**Comment by andreilupu** [comment]
deocamdata raman doar dependentele pe un singur nivel cu inputuri de tipul radio, checkbox, select si text.

**Comment by georgeolaru** [comment]
Completezi putin documentatia? Putem aplica la Heap sa vedem cum merge?

**Comment by andreilupu** [comment]
https://github.com/pixelgrade/customify#conditional-fields

deja lucrez la Heap la asta
