### ISSUE TITLE
Tabs Styling & Logic 

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/customify#41]
Tabs will be used as anchor points for sections (see #40):

![image](https://cloud.githubusercontent.com/assets/1632775/19718731/384e0680-9b6f-11e6-88a5-5eca46613383.png)

[Scrolling interaction recording](https://cl.ly/2o1z1O3k2p09)

**Comment by georgeolaru** [comment]
@cristianfrumusanu acel padding pus general pare sa strice mai mult sectiuni default din customizer. Poate il putem lasa by-default si sa incercam sa asezam modalul cu alte spatieri.

![image](https://cloud.githubusercontent.com/assets/1632775/19849046/9ff86544-9f59-11e6-8a17-4610cd098cfe.png)
![image](https://cloud.githubusercontent.com/assets/1632775/19849070/bb5a2bd8-9f59-11e6-8492-b5fcc967b0eb.png)

**Comment by cristianfrumusanu** [comment]
@georgeolaru
Am ajustat aici.

**Comment by andreilupu** [comment]
vreau sa dau update, mai e ceva de facut aici?

**Comment by georgeolaru** [comment]
Nu, nu cred.
