### ISSUE TITLE
Font Field Defaults and Reset not working

### ISSUE THREAD

**Issue by razwan** [pixelgrade/customify#45]
Defaulturile nu prea functioneaza initial
===
![screen shot 2016-11-28 at 15 59 21](https://cloud.githubusercontent.com/assets/1633371/20712502/efcdf6f6-b64c-11e6-807c-028353534707.png)

Daca dai reset to defaults vor functiona
===
![screen shot 2016-11-29 at 16 01 33](https://cloud.githubusercontent.com/assets/1633371/20712555/29c83470-b64d-11e6-875d-1ff9ebaa1242.png)

Dar in schimb crapa previewul cam asa:
===
![screen shot 2016-11-29 at 15 56 58](https://cloud.githubusercontent.com/assets/1633371/20712577/4d370d96-b64d-11e6-9261-841e53179579.png)

**Comment by andreilupu** [comment]
Am rezolvat problema la default!

Insa, butonul de reset nu a fost facut pentru asa ceva si deocamdata nu avem timp pentru asta
