### ISSUE TITLE
Remove CSS Editor if WP version >= 4.7

### ISSUE THREAD

**Issue by razwan** [pixelgrade/customify#46]
In WP 4.7 au adaugat ei un editor de CSS iar al nostru pare sa nu mai functioneze.
Cred ca trebuie verificata versiunea WP si dezactivat by default al nostru daca e > 4.7

![screen shot 2016-11-30 at 11 32 20](https://cloud.githubusercontent.com/assets/1633371/20747154/b8f3ece4-b6f1-11e6-9bdf-f54ecfac4b7d.png)

**Comment by alinclamba** [comment]
Al nostru era mai fain! 😋

**Comment by razwan** [comment]
Mi se pare un pic mai rapid si ma gandesc ca o sa adauge si ei line numbers si syntax highlighting curand
