### ISSUE TITLE
PHP 5.3.29 and Customify 1.3.0 Issues

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/customify#50]
[Rosa](https://secure.helpscout.net/conversation/288073428/45/?folderId=1083389) (Help Scout) [#2](https://help.pixelgrade.com/helpdesk/tickets/40696)

> Your rosa theme is broke by newest customfy update 2.71 works 3 breaks all most all of the CSS user additions to the theme

[Pile](https://help.pixelgrade.com/helpdesk/tickets/40697) (Freshdesk)
[Listable](https://help.pixelgrade.com/helpdesk/tickets/40694)

> Parse error: syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /home4/techstep/public_html/gemmahenderson.com/wp-content/plugins/customify/features/customizer/controls/class-Pix_Customize_Font_Control.php on line 431
> 
> So I can't access the Customizer.

cc @pixelgrade/heroes cred ca ar ajuta un mesaj canned si marcate ticketele cu tag-ul `customify-1-3-0` ca sa putem reveni la ei dupa.

**Comment by georgeolaru** [comment]
Issue-ul, cel putin la mine, se manifesta pe PHP 5.3.29 — am testat cu 5.6.20 si cu 7.0.3 si merge in regula.

**Comment by allexsava** [comment]
@georgeolaru 

Sorry to hear that you have troubles with your website! We are already aware of this issue and working to release a fix for it. I'll keep you updated!

As a temporary solution, could you please check if you can update your PHP version to 7? It's the version recommended by WordPress itself: https://wordpress.org/about/requirements/

Another temporary fix would be to _downgrade Customify_ to the previous version. You can achieve this by going to _Plugins — All Plugins_ look for the Customify plugin, **Deactivate** and **Delete** it. Now, install the attached archive via _Plugins — Add New_.
[customify.1.2.7.1.zip](https://github.com/pixelgrade/customify/files/635802/customify.1.2.7.1.zip)

**Comment by georgeolaru** [comment]
E bun mesajul, doar ca update-ul la PHP 7 e defapt solutia, nu neaparat una temporara.

**Comment by allexsava** [comment]
Am inteles, am modificat putin mesajul :)

**Comment by allexsava** [comment]
Mesajul de follow up pentru tickete cu tagul customify-1-3-0:

Sorry for any inconveniences caused! We’ve already fixed this issue and all you have to do is update Customify to version 1.3.1.

Let me know how it went. :slightly_smiling_face:
