### ISSUE TITLE
Font field weight wrong value

### ISSUE THREAD

**Issue by cristianfrumusanu** [pixelgrade/customify#51]
Daca selectez 
![image](https://cloud.githubusercontent.com/assets/5011858/21016921/289068aa-bd70-11e6-93d1-8d920069ab8e.png)
imi scoate output
```css
    font-weight: 600italic;
```
in loc de 
```css
    font-weight: 600;
    font-style: italic;
```

**Comment by andreilupu** [comment]
not a plugin issue see pixelgrade/noah#231
