### ISSUE TITLE
Font field errors after navigation

### ISSUE THREAD

**Issue by cristianfrumusanu** [pixelgrade/customify#53]
Scenariu: sunt pe pagina de Journal si intru un Customizer. Modific niste font-uri pe pagina de Journal.
Apoi navighez pe un single post si intru sa modific niste font-uri pentru Single Post (in sectiunea Main Content). Cand deschid un field de font, apare eroarea in consola.

```javascript
VM18460 font_selector_preview.js?ver=4.7:100 
Uncaught TypeError: Cannot read property 'noah_font_typeline_cb' of null(…)
```
https://cloudup.com/ckD-fQj8YHU

LE: alt scenariu mai simplu
https://cloudup.com/c4FqNyX1v6P

**Comment by andreilupu** [comment]
issue-ul vine din noah si din cate vad a fost reparat
