### ISSUE TITLE
Incorrect Color Panel Height 

### ISSUE THREAD

**Issue by allexsava** [pixelgrade/customify#54]
Am reusit sa identific asta pe Timber 1.6.6 cu WP 4.7 si Customify 1.3.1;

![screen shot 2016-12-09 at 16 31 33](https://cloud.githubusercontent.com/assets/3309914/21053388/da2933fa-be31-11e6-8d2c-2d0054f74f72.png)

@andreilupu nu a functionat solutia cu "shift+refresh", predau stafeta la @cristianfrumusanu sa dea o parere

**Comment by cristianfrumusanu** [comment]
Am rezolvat aici si am testat in Customizer la Mies si la Noah.

**Comment by Robertght** [comment]
We good 👍
