### ISSUE TITLE
No tabs on section removes space between first options

### ISSUE THREAD

**Issue by alexandra-budeanu** [pixelgrade/customify#57]
![423a1f36e1d1390461b68864e4a8eaa2 _image 202017-02-06 20at 205 01 28 20pm](https://cloud.githubusercontent.com/assets/24452073/22652149/fe0025f6-ec8d-11e6-81b9-2444eac40491.png)

The issue is this line of code:
![74e111eaee08886d474dc18d5328a947 _image 202017-02-06 20at 205 02 51 20pm](https://cloud.githubusercontent.com/assets/24452073/22652184/2d65ed6c-ec8e-11e6-917c-9641fe925187.png)

**Comment by cristianfrumusanu** [comment]
https://github.com/pixelgrade/customify/commit/a5089cdc51e414e6a63b9362905f976733595c78
