### ISSUE TITLE
Style Presets Font issue

### ISSUE THREAD

**Issue by alexandra-budeanu** [pixelgrade/customify#67]
Cand selectez un Style Preset, in CSS imi pune font-family corect, dar nu este inclus si linkul catre google fonts, asa ca nu recunoaste fontul. Am testat pe versiunile 1.3.1 si 1.4.1

**Comment by allexsava** [comment]
bump bump @andreilupu avem nevoie de asta pentru update-ul la Patch :D

**Comment by andreilupu** [comment]
update-ul la Customify e in plan saptamana asta, rabdare
