### ISSUE TITLE
Style Conflict with Jetpack Visibility Widgets

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/customify#76]
Selectorii din cauza reset-ului unor width-uri arata cam asa:
![image](https://cloud.githubusercontent.com/assets/1632775/24096629/19f684be-0d6b-11e7-8eee-2d74d74abbd8.png)

Pe WordPress.com arata cam asa:
![image](https://cloud.githubusercontent.com/assets/1632775/24096659/37b0db6c-0d6b-11e7-9e80-76a1373883f8.png)

Un inceput de solutie ar fi sa adaugam un padding pe select `padding: 7px 32px 9px 14px;`

**Comment by cristianfrumusanu** [comment]
![image](https://cloud.githubusercontent.com/assets/5011858/26832482/4c1a89f4-4ad8-11e7-9c49-cc3a0d32a730.png)
