### ISSUE TITLE
Items Aspect Ratio: Change from Slider to Radio Buttons/Dropdown

### ISSUE THREAD

**Issue by ilincaroman** [pixelgrade/customify#77]
**[UI/UX]**
Cand un user stie ca item-urile o sa fie "Original Aspect Ratio" (ratio-ul lor initial)?
Cum pot reveni la Original Aspect Ratio daca au modificat deja din slider valoarea?
Inca nu cred ca un slider e reprezentativ pentru un Aspect Ratio si sugerez macar sa fie modificat la un Drop Down sau Radio Buttons cu mai putine optiuni (cele standard spre exemplu: 16:9; 4:3; 3:2; 1:1 or so)

![](https://puu.sh/uVFwf/1cd6b50d44.png)

Am inclus oricum un task pe asta si la User Testing, vedem ce se intampla. 

@georgeolaru 
Also nu pot sa pun Label-uri pe issue-ul asta :/

**Comment by georgeolaru** [comment]
@ilincaroman aici ar trebui implementat sistemul de field-uri dependente: https://github.com/pixelgrade/customify/issues/35

De exemplu "Items Aspect Ratio" dela Noah are sens sa apara doar in cazul in care selectezi "Regular Grid". In cazul in care implementam sistemul, ar trebui sa schimbam si descrierea si sa scoatem treaba cu "original ratio".
