### ISSUE TITLE
Customizer changes saved per theme mod

### ISSUE THREAD

**Issue by Robertght** [pixelgrade/customify#81]
Daca avem in Settings->Customify-> **Store values as: Per theme** si o tema parinte + child, setarile din customizer vor fi salvate per tema. Adica daca schimb de pe child theme cu ceva setari din customizer, pe parinte, ele nu-s acolo. 

Am schimbat pe Option (global options) ca sa mearga si una si alta, insa facand asta am pierdut setarile anterior facute in customizer.

**Comment by andreilupu** [comment]
Soo, ca sa pot inchide acest issue.

Option = Un mod de a stoca informatia global.

Theme Mod = Un mod de a stoca informatia doar pentru tema activa. Deci daca schimbi tema de pe parinte pe child, schimbi si locatia unde sunt salvate optiunile.

This is how it works
