### ISSUE TITLE
A small style issue

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/customify#84]
Problema am vauzt-o la Pile dupa update-ul Customify la 1.5.3 — apare la optiunile care au titlu si checkbox, cum ar fi:

-  **Theme Options > General**

![image 2017-06-07 at 11 08 42 pm](https://user-images.githubusercontent.com/6790170/26899157-fcf23f2a-4bd6-11e7-8868-ae6fd8e5dc85.png)

**- Layout > Portfolio Archive**

![image 2017-06-07 at 11 48 07 pm](https://user-images.githubusercontent.com/6790170/26900815-2413513e-4bdc-11e7-8b8c-f8232869b75d.png)

**- Layout > Single Project**

![screenshot at jun 07 23-52-16](https://user-images.githubusercontent.com/6790170/26900878-6ae4142c-4bdc-11e7-8b85-2eda3556ff75.png)

Si in toate celelalte locuri cu optiuni de acest gen.

**Comment by vladolaru** [comment]
@cristianfrumusanu Poti rezolva asta ca e destul de nasola? Ca sa prinda update-ul de saptamana asta.

https://github.com/pixelgrade/customify/blob/dev/scss/customizer.scss#L288
