### ISSUE TITLE
Add Support for "0" Values

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/customify#85]
In procesul de scriere a default-urilor pentru Timber (porning de la Noah), m-am intalnit destul de des cu situatia cand e ignorat un default cu valoarea `0`.

De exemplu la componente, am un caz la fieldul de fonturi care e definit by-default cu un `letter-spacing: 0.28` insa eu as avea nevoie sa fie 0, sa suprascrie o regula mai generala.

@andreilupu @andreistangacianu incercam sa gasim o solutie?

**Comment by andreilupu** [comment]
fiexd
