### ISSUE TITLE
Consistent Fonts Names Loaded via Fonto Plugin

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/customify#86]
In preview-ul din Customify apare "Font Family Name" in timp ce in select apare titlul fontului: 
![image](https://user-images.githubusercontent.com/1632775/26968882-5f477b96-4d0c-11e7-8cd6-8ce0b8468a3e.png)

**Comment by andreilupu** [comment]
Am studiat putin problema aici si cred ca acel select este creat de Fonto, asa ca o sa pun issue-ul acolo
