### ISSUE TITLE
Backend editor text get the color of body text

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/customify#88]
Sa zicem ca vrei ca body text sa aiba culoarea verde si setezi asta din _Customizer > Fonts_. Problema insa consta in faptul ca si in backend culoarea va fi aceeasi si poate deveni greu de editat (in cazul asta cu [verde](https://cl.ly/3R3t1o1b1d2P)).

Am observat ca daca activezi alta tema, gen Twenty Seventeen, problema dispare. Adica nu conteaza ce culoare setezi pentru body text, editorul din backend va avea mereu culoarea neagra. 

Am testat cu doua teme - Osteria si Listable si problema e la fel. 

_(nu am reusit sa scriu un titlu mai reprezentativ insa am incercat prin detalii sa explic problema)_

**Comment by andreilupu** [comment]
@alinclamba exista o optiune in Customify -> Settings pentru aplicarea stilurilor din Customify in editorul WordPress-ului.

Dar inainte de a dezactiva acea optiune ar trebui sa te gandesti ca acel stil, incearca sa ii ofere utilizatorului o imagine cat mai fidela a articolului inainte de a fi publicat.
In cazul tau, daca acel verde este greu de editat, inseamna ca este si greu de citit de utilizatori si nu ar trebui sa folosesti din start culoarea aia.
