### ISSUE TITLE
Select for woocommerce category

### ISSUE THREAD

**Issue by kinolanka** [pixelgrade/customify#89]
I need user to choose some of woocommerce category so I create select field this way:

```php
$args = array(
			'taxonomy' => 'product_cat',
			'hide_empty' => false,
                        'fields' => 'id=>name',
			);
$cats_arr = get_terms( $args );

...

"woo_cat" => array(
					'type'    => 'select',
					'label'   => __( 'Woo category' ),
					'choices' => $cats_arr
);
```

But WP_Error occured: invalid taxonomy.

**Comment by andreilupu** [comment]
Hi, I'm sorry for missing this issue for such a long time!

I don't think this is a Customify issue. From what I can see this is a problem with the core function `get_terms` and the only advice that I have for you is to check that the taxonomy really exists.
