### ISSUE TITLE
WordPress 4.9 Styling Glitches

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/customify#91]
Am trecut putin prin Customify cu versiunea beta de WordPress 4.9 si am gasit urmatoarele pe partea de frontend:

- [x] La selectorii de culoare apare label-ul "Select Color": https://cl.ly/2h2k00253t2z
- [x] Butoanele de Responsive Preview din footer sunt pozitionate prea jos (s-ar putea sa nu fie din Customify dar trebuie testat): https://cl.ly/1O3c453J053w
- [x] Noul buton de Save/Publish ar trebui sa aiba textu aliniat si iconita de "Settings" delimitata printr-un border sau background: https://cl.ly/250L2R1z3S22

**Comment by alinclamba** [comment]
- [ ] Elementele din sectiunea _Site Identity_ trebuie putin aliniate: https://cl.ly/1n3U442F220A
- [ ] Acolo unde se deschide inca un modal cu optiuni, cum ar fi la Listable: _Widgets → Front Page Sections → Spotlights_, noile optiuni legate de butonul **Publish** nu sunt afisate: https://cl.ly/2c052k1g3m2k

**Comment by georgeolaru** [comment]
@alinclamba am rezolvat doua din ele — cel cu Listable, fiind un caz destul de izolat, ramane pe altadata :)
