### ISSUE TITLE
Fatal error when trying to upgrade WordPress version

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/customify#93]
Am [un client](https://secure.helpscout.net/conversation/453861440/25903?folderId=1142154) cu Gema care a incercat sa faca ieri update la WordPress si a obtinut asta:
>**Deprecated:** Non-static method PixCustomifyPlugin::get_option() should not be called statically in C:\domains\dekleinewolf.com\wwwroot\wp-content\themes\gema\inc\integrations\customify.php on line 685

> **Fatal error:** Uncaught Error: Using $this when not in object context in C:\domains\dekleinewolf.com\wwwroot\wp-content\plugins\customify\class-pixcustomify.php:1869 Stack trace: #0 C:\domains\dekleinewolf.com\wwwroot\wp-content\themes\gema\inc\integrations\customify.php(685): PixCustomifyPlugin::get_option('background_colo...') #1 C:\domains\dekleinewolf.com\wwwroot\wp-content\plugins\customify\class-pixcustomify.php(983): gema_dropcap_gradient('#000', '.is--webkit .dr...', 'background', '') #2 C:\domains\dekleinewolf.com\wwwroot\wp-content\plugins\customify\class-pixcustomify.php(959): PixCustomifyPlugin->proccess_css_property(Array, '#000') #3 C:\domains\dekleinewolf.com\wwwroot\wp-content\plugins\customify\class-pixcustomify.php(538): PixCustomifyPlugin->convert_setting_to_css('body_color', Array) #4 C:\domains\dekleinewolf.com\wwwroot\wp-content\plugins\customify\class-pixcustomify.php(1040): PixCustomifyPlugin->output_dynamic_style() #5 C:\domains\dekleinewolf.com\wwwroot\wp-includes\plugin.php(524): PixCustomifyPlugi in C:\domains\dekleinewolf.com\wwwroot\wp-content\plugins\customify\class-pixcustomify.php on line 1869

**Comment by andreilupu** [comment]
@alinclamba Mai cu grija, repo-ul asta e public.
 Ti-am sters eu datele de access de acolo.

**Comment by alinclamba** [comment]
@andrei mersi, my bad. 
Pana la urma s-a dovedit a fi devina versiunea mai veche a temei pe care o avea clientul instalata. S-a rezolvat, asa ca voi inchide aici si daca mai apar cazuri similare redeschidem.
